### ISSUE TITLE
Out of range error voice

### ISSUE THREAD

**Issue by Bokoa** [anzz1/TacoTip#2]
I've been getting "out of range" error voice line over and over in BGs specifically AV.
It stopped upon disabling this addon so I think this must be causing it.

**Comment by anzz1** [comment]
Oh yeah, the blizzard's implementation for "CanInspect" is broken, as it doesn't respect the "showError" argument. I fixed the implementation to not show the UI error message, but I've never played with error *sounds* on, so never noticed that.
I'll fix it " soon™ "

**Comment by Bokoa** [comment]
Nice, i’ll try the workaround by now. Thanks!

**Comment by anzz1** [comment]
Fixed in [0.2.8](https://github.com/anzz1/TacoTip/releases/tag/0.2.8)
