### ISSUE TITLE
Please Add "TacoTip_Wrath.toc" for classic wrath

### ISSUE THREAD

**Issue by codeduph** [anzz1/TacoTip#20]
just for convince sake...

its it kinda annoying every update I'm prompted with disable outdated addon... and have to edit the toc to "## Interface: 30400"... when you can simply add it...

![2022-11-18_204505](https://user-images.githubusercontent.com/16449014/202709035-59cd97bd-3959-477f-8044-3f7aa118ee1e.png)
![2022-11-18_204927](https://user-images.githubusercontent.com/16449014/202709043-5a88c7c7-7909-4ba3-85f9-f0735b109d05.png)

**Comment by anzz1** [comment]
duplicate of #9 

discussion cont. in #21
