### ISSUE TITLE
Conflict with Krowi's Achievement Filter

### ISSUE THREAD

**Issue by Iowerth** [anzz1/TacoTip#23]
Hi. I've found conflict between TacoTip and Krowi's Achievement Filter - [CurseForge](https://www.curseforge.com/wow/addons/krowi-achievement-filter), [GitHub](https://github.com/TheKrowi/Krowi_AchievementFilter).
If only TacoTip and KAF are enabled then KAF showing incorrect information, I need to `/reload`.
If TacoTip disabled then all fine.

May you please figure it out with KAF's author @TheKrowi?

**Comment by anzz1** [comment]
Hey and thanks for your report, I'll contact the author

**Comment by anzz1** [comment]
The conflict should be fixed with https://github.com/anzz1/TacoTip/commit/398dd35ee61c1e1c1dfe1d07b7705c5855d5e11c

**Comment by anzz1** [comment]
Fixed in release [0.3.5](https://github.com/anzz1/TacoTip/releases/tag/0.3.5)
