### ISSUE TITLE
Custom anchors

### ISSUE THREAD

**Issue by sfjuocekr** [anzz1/TacoTip#3]
Could you implement custom anchor locations?

I'd like to have unit tooltips on my mouse for example.

TinyTooltip has a good example of how you could implement this, I have modified its behavior by changing the following bit in core.lua so it ignores mouseover tooltips on the raid frame:

```
hooksecurefunc("GameTooltip_SetDefaultAnchor", function(self, parent)
    if GetMouseFocus() ~= WorldFrame then return end
    LibEvent:trigger("tooltip:anchor", self, parent)
end)
```

**Comment by anzz1** [comment]
Sure, I've been on a temporary hiatus but I'll be sure to add this option in a future release.

**Comment by sfjuocekr** [comment]
Also the newly added "you" for target could be accentuated by the color red and capitalized!

**Comment by anzz1** [comment]
I was also thinking of an option which could color the frame borders, if an enemy is targetting you=yellow / enemy in combat&targetting you=red (meaning npc is aggroing you, or a player is on pvp combat and targeting you)

**Comment by sfjuocekr** [comment]
That is a great idea, but the class color is already the border. Maybe making the background class/reaction based is an idea as well.

I am also missing location, when I mouseover someone now I can't tell in which zone they are.

**Comment by sfjuocekr** [comment]
Ok maybe I was just blind, because I do see locations now...

**Comment by anzz1** [comment]
- "Anchor to Mouse" added in [v0.2.9](https://github.com/anzz1/TacoTip/releases/tag/0.2.9)

- "Custom Tooltip Position" was already an option in v0.2.1.
