### ISSUE TITLE
[Bug] Missing Glyph of Reckoning likely causing Lua Error

### ISSUE THREAD

**Issue by leetified86** [anzz1/TacoTip#35]
Getting an error right now after the addition of the new glyph on my Paladin.  

Message: ...Tip/Libs/LibClassicInspector-9/LibClassicInspector.lua:3099: attempt to perform arithmetic on field '?' (a nil value)
Time: Wed Feb  8 17:31:57 2023
Count: 1
Stack: ...Tip/Libs/LibClassicInspector-9/LibClassicInspector.lua:3099: attempt to perform arithmetic on field '?' (a nil value)

**Comment by anzz1** [comment]
Should be fixed in [0.3.6](https://github.com/anzz1/TacoTip/releases/tag/0.3.6) . Couldn't test it right now, so please report back if it doesn't work.
